package NullLayou;

import Class.Class_TaiKhoan;
import DAO.DAO_QuenMK;
import DAO.KetNoi;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.font.TextAttribute;
import java.util.Map;
import javax.swing.DebugGraphics;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

public class QuenMatKhau extends javax.swing.JFrame {

    KetNoi cn = new KetNoi();
    public static String tk;

    public QuenMatKhau() {
        initComponents();
        ImageIcon i = new ImageIcon("E:\\1 Tai Nguyen JAVA3\\SOF203\\Lythuyet5\\File rieng\\AnhDep.png");
        // ImageIcon i = new ImageIcon("‪E:\\1 Tai Nguyen JAVA3\\SOF203\\LyThuyet1\\Group 244.png");
        lbAnh.setIcon(i);
        this.setIconImage(new ImageIcon("E:\\1 Tai Nguyen JAVA3\\SOF203\\Lythuyet5\\File rieng\\foursquare.png").getImage());
//        JLabel lb = new JLabel(i);
//        lb.setSize(700, 570);
        this.setSize(1100, 650);
        pnlAnh.add(lbAnh);
        // lblLoi.setVisible(false);
        // frameInit();

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        jPanel1 = new JPanel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel2 = new JLabel();
        txtMail = new JTextField();
        pnlAnh = new JPanel();
        lbAnh = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(255, 255, 255));
        setIconImages(null);

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("Đăng nhập"), this, BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(null);

        jPanel1.setBackground(new Color(255, 255, 255));

        jLabel3.setIcon(new ImageIcon("C:\\Users\\My PC\\Desktop\\ERD\\photo\\btn_login.png")); // NOI18N
        jLabel3.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Please enter your account");

        jLabel2.setIcon(new ImageIcon("C:\\Users\\My PC\\Desktop\\ERD\\Path 297.png")); // NOI18N
        jLabel2.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent evt) {
                jLabel2FocusLost(evt);
            }
        });

        txtMail.setText("UseName");
        txtMail.setBorder(null);
        txtMail.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                txtMailFocusGained(evt);
            }
            public void focusLost(FocusEvent evt) {
                txtMailFocusLost(evt);
            }
        });
        txtMail.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMail, GroupLayout.PREFERRED_SIZE, 275, GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel4)
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMail, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(541, 0, 560, 650);

        GroupLayout pnlAnhLayout = new GroupLayout(pnlAnh);
        pnlAnh.setLayout(pnlAnhLayout);
        pnlAnhLayout.setHorizontalGroup(pnlAnhLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnhLayout.createSequentialGroup()
                .addComponent(lbAnh, GroupLayout.PREFERRED_SIZE, 539, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlAnhLayout.setVerticalGroup(pnlAnhLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(lbAnh, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        getContentPane().add(pnlAnh);
        pnlAnh.setBounds(0, 0, 539, 650);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        tk = txtMail.getText().trim();

        boolean a = DAO.DAO_QuenMK.TaiKhoan(tk);
        if (a) {

            DAO_QuenMK.GuiMail(tk);
            System.out.println("t");
            this.dispose();

        } else {
            System.out.println("a");
        }
        // tk.setTenMail(txtAcount.getText());

    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtMailActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    private void txtMailFocusGained(FocusEvent evt) {//GEN-FIRST:event_txtMailFocusGained
        if (txtMail.getText().trim().equals("UseName")) {
            txtMail.setText("");
            txtMail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtMailFocusGained

    private void jLabel2FocusLost(FocusEvent evt) {//GEN-FIRST:event_jLabel2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2FocusLost

    private void txtMailFocusLost(FocusEvent evt) {//GEN-FIRST:event_txtMailFocusLost
        if (txtMail.getText().trim().equals("")) {
            txtMail.setText("UseName");
            txtMail.setForeground(Color.decode("#E8E9EC"));
        }
    }//GEN-LAST:event_txtMailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JLabel jLabel2;
    JLabel jLabel3;
    JLabel jLabel4;
    JPanel jPanel1;
    JLabel lbAnh;
    JPanel pnlAnh;
    JTextField txtMail;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
