package NullLayou;

import Class.Class_TaiKhoan;
import DAO.KetNoi;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.font.TextAttribute;
import java.util.Map;
import javax.swing.DebugGraphics;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

public class XacNhanMK extends javax.swing.JFrame {

    KetNoi cn = new KetNoi();

    public XacNhanMK() {
        initComponents();
        ImageIcon i = new ImageIcon("E:\\1 Tai Nguyen JAVA3\\SOF203\\Lythuyet5\\File rieng\\AnhDep.png");
        // ImageIcon i = new ImageIcon("‪E:\\1 Tai Nguyen JAVA3\\SOF203\\LyThuyet1\\Group 244.png");
        lbAnh.setIcon(i);
        this.setIconImage(new ImageIcon("E:\\1 Tai Nguyen JAVA3\\SOF203\\Lythuyet5\\File rieng\\foursquare.png").getImage());
//        JLabel lb = new JLabel(i);
//        lb.setSize(700, 570);
        this.setSize(1100, 650);
        pnlAnh.add(lbAnh);
        // lblLoi.setVisible(false);
        // frameInit();
        //  System.out.println(QuenMatKhau.tk);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        jPanel1 = new JPanel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel2 = new JLabel();
        txtMaOTP = new JTextField();
        txtPas = new JPasswordField();
        lblThangNgang = new JLabel();
        lblThangNgang1 = new JLabel();
        txtPas1 = new JPasswordField();
        pnlAnh = new JPanel();
        lbAnh = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(255, 255, 255));
        setIconImages(null);

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, this, ELProperty.create("Đăng nhập"), this, BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(null);

        jPanel1.setBackground(new Color(255, 255, 255));

        jLabel3.setIcon(new ImageIcon("C:\\Users\\My PC\\Desktop\\ERD\\photo\\btn_login.png")); // NOI18N
        jLabel3.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Welcome back! Please login to your account");

        jLabel2.setIcon(new ImageIcon("C:\\Users\\My PC\\Desktop\\ERD\\Path 297.png")); // NOI18N
        jLabel2.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent evt) {
                jLabel2FocusLost(evt);
            }
        });

        txtMaOTP.setText("Nhập mã OTP");
        txtMaOTP.setBorder(null);
        txtMaOTP.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                txtMaOTPFocusGained(evt);
            }
            public void focusLost(FocusEvent evt) {
                txtMaOTPFocusLost(evt);
            }
        });
        txtMaOTP.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtMaOTPActionPerformed(evt);
            }
        });

        txtPas.setText("Password");
        txtPas.setBorder(null);
        txtPas.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        txtPas.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                txtPasFocusGained(evt);
            }
            public void focusLost(FocusEvent evt) {
                txtPasFocusLost(evt);
            }
        });
        txtPas.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtPasActionPerformed(evt);
            }
        });

        lblThangNgang.setIcon(new ImageIcon("C:\\Users\\My PC\\Desktop\\ERD\\Path 297.png")); // NOI18N

        lblThangNgang1.setIcon(new ImageIcon("C:\\Users\\My PC\\Desktop\\ERD\\Path 297.png")); // NOI18N

        txtPas1.setText("Password1");
        txtPas1.setBorder(null);
        txtPas1.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                txtPas1FocusGained(evt);
            }
            public void focusLost(FocusEvent evt) {
                txtPas1FocusLost(evt);
            }
        });
        txtPas1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtPas1ActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(lblThangNgang1, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaOTP, GroupLayout.PREFERRED_SIZE, 288, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPas1, GroupLayout.PREFERRED_SIZE, 279, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblThangNgang, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(txtPas, GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                    .addGap(142, 142, 142)))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaOTP, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(lblThangNgang1, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPas1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(305, 305, 305)
                    .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(lblThangNgang, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPas, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(305, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(541, 0, 560, 650);

        GroupLayout pnlAnhLayout = new GroupLayout(pnlAnh);
        pnlAnh.setLayout(pnlAnhLayout);
        pnlAnhLayout.setHorizontalGroup(pnlAnhLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnhLayout.createSequentialGroup()
                .addComponent(lbAnh, GroupLayout.PREFERRED_SIZE, 539, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlAnhLayout.setVerticalGroup(pnlAnhLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(lbAnh, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        getContentPane().add(pnlAnh);
        pnlAnh.setBounds(0, 0, 539, 650);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaOTPActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtMaOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaOTPActionPerformed

    private void txtMaOTPFocusLost(FocusEvent evt) {//GEN-FIRST:event_txtMaOTPFocusLost
        if (txtMaOTP.getText().trim().equals("")) {
            txtMaOTP.setText("Nhập mã OTP");
            txtMaOTP.setForeground(Color.decode("#E8E9EC"));
        }
    }//GEN-LAST:event_txtMaOTPFocusLost

    private void txtMaOTPFocusGained(FocusEvent evt) {//GEN-FIRST:event_txtMaOTPFocusGained
        if (txtMaOTP.getText().trim().equals("Nhập mã OTP")) {
            txtMaOTP.setText("");
            txtMaOTP.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtMaOTPFocusGained

    private void jLabel2FocusLost(FocusEvent evt) {//GEN-FIRST:event_jLabel2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2FocusLost

    private void jLabel3MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        String OTP = txtMaOTP.getText();
        String MK = txtPas.getText();
        String MK1 = txtPas1.getText();
        boolean a = DAO.DAO_QuenMK.KtraXN(OTP, MK, MK1);
        if (a) {
            DAO.DAO_TaiKhoan.update(MK1);
            System.out.println("Ok");

        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtPas1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtPas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPas1ActionPerformed

    private void txtPasActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtPasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasActionPerformed

    private void txtPasFocusLost(FocusEvent evt) {//GEN-FIRST:event_txtPasFocusLost
        if (String.valueOf(txtPas.getPassword()).equals("")) {
            txtPas.setText("Password");
            txtPas.setForeground(Color.decode("#E8E9EC"));
        }
    }//GEN-LAST:event_txtPasFocusLost

    private void txtPasFocusGained(FocusEvent evt) {//GEN-FIRST:event_txtPasFocusGained
        if (String.valueOf(txtPas.getPassword()).equals("Password")) {
            txtPas.setText("");
            txtPas.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPasFocusGained

    private void txtPas1FocusGained(FocusEvent evt) {//GEN-FIRST:event_txtPas1FocusGained
        if (String.valueOf(txtPas1.getPassword()).equals("Password1")) {
            txtPas1.setText("");
            txtPas1.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPas1FocusGained

    private void txtPas1FocusLost(FocusEvent evt) {//GEN-FIRST:event_txtPas1FocusLost
        if (String.valueOf(txtPas1.getPassword()).equals("")) {
            txtPas1.setText("Password1");
            txtPas1.setForeground(Color.decode("#E8E9EC"));
        }
    }//GEN-LAST:event_txtPas1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XacNhanMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XacNhanMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XacNhanMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XacNhanMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XacNhanMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JLabel jLabel2;
    JLabel jLabel3;
    JLabel jLabel4;
    JPanel jPanel1;
    JLabel lbAnh;
    JLabel lblThangNgang;
    JLabel lblThangNgang1;
    JPanel pnlAnh;
    JTextField txtMaOTP;
    JPasswordField txtPas;
    JPasswordField txtPas1;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
